Tests: take care of JSON VM tests output (#582)
Improve JSON test debug experience with the following changes:
1. Expected and actual items are accidentally swapped in some overloads
   of `AssertResult` which leads to a mileading test output.
2. Rename parameters of `AssertResult` so that it's easier to distinguish
   expected and actual. No functional changes.
3. Adjust formatting of output messages (add missing spaces, rephrase
   some messages to be more presize, remove blamk lines). No functional
   changes.

E.g. before:
```
  Neo.VM.Tests test net10.0 failed with 1 error(s) (0.9s)
    /home/anna/Documents/GitProjects/neo-project/neo-vm/tests/Neo.VM.Tests/VMJsonTestBase.cs(324): error TESTERROR:
      TestOthers (164ms): Error Message: Test method Neo.Test.UT_VMJson.TestOthers threw exception:
      System.AggregateException: Error in file: /home/anna/Documents/GitProjects/neo-project/neo-vm/tests/Neo.VM.Tests/bin/Debug/net10.0/Tests/Others/ReferenceCounter.json (Others-Reference
      counter-Circular reference - A -> B -> A; clear A:  [Invocation stack] [EvaluationStack]Stack is different
      Expected:
      4
      Actual:
      3) ---> System.Exception: Others-Reference counter-Circular reference - A -> B -> A; clear A:  [Invocation stack] [EvaluationStack]Stack is different
      Expected:
      4
      Actual:
      3
      Stack Trace:
...
```
After:
```
  Neo.VM.Tests test net10.0 failed with 1 error(s) (1.2s)
    /home/anna/Documents/GitProjects/neo-project/neo-vm/tests/Neo.VM.Tests/VMJsonTestBase.cs(324): error TESTERROR:
      TestOthers (165ms): Error Message: Test method Neo.Test.UT_VMJson.TestOthers threw exception:
      System.AggregateException: Error in file: /home/anna/Documents/GitProjects/neo-project/neo-vm/tests/Neo.VM.Tests/bin/Debug/net10.0/Tests/Others/ReferenceCounter.json (Others-Reference
      counter-Circular reference - A -> B -> A; clear A:  [Invocation stack] [EvaluationStack] Stack has unexpected length
      Expected:
      3
      Actual:
      4) ---> System.Exception: Others-Reference counter-Circular reference - A -> B -> A; clear A:  [Invocation stack] [EvaluationStack] Stack has unexpected length
      Expected:
      3
      Actual:
      4
      Stack Trace:
...
```

Signed-off-by: Anna Shaleva <shaleva.ann@nspcc.ru>